version = 0.1

[main.deploy.parameters]
stack_name = "R4B-VPC-Main"
resolve_s3 = true
s3_prefix = "R4B-VPC-Main"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"main\" AppName=\"R4B-VPC\""
image_repositories = []

[demo.deploy.parameters]
stack_name = "R4B-VPC-Demo"
resolve_s3 = true
s3_prefix = "R4B-VPC-Demo"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"demo\" AppName=\"R4B-VPC\""
image_repositories = []

[dev.deploy.parameters]
stack_name = "R4B-VPC-Dev"
resolve_s3 = true
s3_prefix = "R4B-VPC-Dev"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\" AppName=\"R4B-VPC\""
image_repositories = []