INTERNAL_TO_INDEED_TITLES = {
    "Customer Service Representative": ["Customer Service Representative"],
    "Electrician": ["Electrician", "Journeyman Electrician", "Master Electrician"],
    "Field Supervisor": ["HVAC Supervisor", "Field Supervisor", "HVAC Foreman"],
    "Full Charge Bookkeeper": ["Full Charge Bookkeeper", "Bookkeeper"],
    "General Manager": ["General Manager", "HVAC General Manager", "General Operations Manager"],
    "Home Solutions Advisor": ["Home Solutions Advisor", "Comfort Consultant", "In Home Sales Representative", "Outside Sales Rep", "Comfort Advisor"],
    "HVAC Installer": ["HVAC Installer", "Installer"],
    "HVAC Service Technician": ["HVAC Service Technician", "Service Technician", "HVAC Technician","Heating, Ventilation & Air Conditioning (HVAC) Technician"],
    "Installation Coordiantor": ["Install Coordinator", "Installation Coordinator", "Scheduling Coordinator", "HVAC Install Coordinator"],
    "Installation Manager": ["HVAC Foreman", "HVAC Install Manager", "HVAC Manager", "HVAC Installation Manager"],
    "Office Assistant": ["Office Assistant"],
    "Plumber": ["Plumber", "Journeyman Plumber", "Service Plumber"],
    "Project Estimator": ["Project Estimator", "Commercial Estimator"],
    "Project Manager": ["Project Manager"],
    "Receptionist": ["Receptionist"],
    "Sales Coordinator": ["Sales Coordinator"],
    "Sales Manager": ["Sales Manager", "HVAC Sales Manager"],
    "Service Dispatcher": ["Service Dispatcher", "Dispatcher", "Service Coordinator", "HVAC Dispatcher"],
    "Service Manager": ["HVAC Service Manager", "Service Manager", "HVAC Manager"],
    "Warehouse Manager": ["Warehouse Manager", "Warehouse Supervisor"],
    "Warehouse Person/Parts Runner": ["Warehouse Parts Runner", "Warehouse Assistant", "Warehouse Worker"]
}
